apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: flotte-dev
data:
  KAFKA_BROKER: "kafka:9092"
  SVC_VEHICULES_URL: "http://svc-vehicules:3001"
  SVC_CONDUCTEURS_URL: "http://svc-conducteurs:3002"
  SVC_MAINTENANCE_URL: "http://svc-maintenance:3005"
  SVC_LOCALISATION_URL: "http://svc-localisation:3004"
  SVC_EVENEMENTS_URL: "http://svc-evenements:3003"
  KEYCLOAK_URL: "http://keycloak:8080"
