apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-localisation
  namespace: flotte-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svc-localisation
  template:
    metadata:
      labels:
        app: svc-localisation
    spec:
      containers:
        - name: svc-localisation
          image: svc-localisation:v2
          imagePullPolicy: Never
          ports:
            - containerPort: 3004
            - containerPort: 50051
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: timescaledb-secret
                  key: DB_URL_LOCALISATION
            - name: KAFKA_BROKER
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: KAFKA_BROKER
            - name: PORT
              value: "3004"
          readinessProbe:
            httpGet:
              path: /health
              port: 3004
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: svc-localisation
  namespace: flotte-dev
spec:
  selector:
    app: svc-localisation
  ports:
    - name: http
      port: 3004
      targetPort: 3004
    - name: grpc
      port: 50051
      targetPort: 50051
  type: ClusterIP
