grafana:
  enabled: true
  adminPassword: "grafana_password_dev"
  persistence:
    enabled: false
  resources:
    limits:
      memory: 256Mi
      cpu: "250m"
    requests:
      memory: 128Mi
      cpu: "100m"

prometheus:
  prometheusSpec:
    retention: 24h
    resources:
      limits:
        memory: 512Mi
        cpu: "500m"
      requests:
        memory: 256Mi
        cpu: "250m"

alertmanager:
  enabled: false

nodeExporter:
  enabled: false

kubeStateMetrics:
  enabled: true
