auth:
  password: "redis_password_dev"
master:
  persistence:
    enabled: true
    size: 512Mi
  resources:
    limits:
      memory: 256Mi
      cpu: "250m"
    requests:
      memory: 128Mi
      cpu: "100m"
replica:
  replicaCount: 0
