apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: flotte-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "4000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: api-gateway
          image: api-gateway:v8
          imagePullPolicy: Never
          ports:
            - containerPort: 4000
          env:
            - name: PORT
              value: "4000"
            - name: SVC_VEHICULES_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SVC_VEHICULES_URL
            - name: SVC_CONDUCTEURS_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SVC_CONDUCTEURS_URL
            - name: SVC_MAINTENANCE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SVC_MAINTENANCE_URL
            - name: SVC_LOCALISATION_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SVC_LOCALISATION_URL
            - name: SVC_EVENEMENTS_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SVC_EVENEMENTS_URL
            - name: KEYCLOAK_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: KEYCLOAK_URL
            - name: KEYCLOAK_REALM
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: KEYCLOAK_REALM
            - name: KEYCLOAK_CLIENT_ID
              value: "gestion-flotte-api"
            - name: KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: KEYCLOAK_SECRET
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector-opentelemetry-collector:4317"
            - name: OTEL_SERVICE_NAME
              value: "api-gateway"
          resources:
            limits:
              cpu: "250m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 4000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 4000
            initialDelaySeconds: 5
            periodSeconds: 10
