apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-conducteurs
  namespace: flotte-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svc-conducteurs
  template:
    metadata:
      labels:
        app: svc-conducteurs
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3002"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: svc-conducteurs
        image: svc-conducteurs:dev
        imagePullPolicy: Never
        ports:
        - containerPort: 3002
        env:
        - name: PORT
          value: "3002"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-collector-opentelemetry-collector:4317"
        - name: OTEL_SERVICE_NAME
          value: "svc-conducteurs"
        resources:
          limits:
            memory: 256Mi
            cpu: "250m"
          requests:
            memory: 128Mi
            cpu: "100m"
