apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-evenements
  namespace: flotte-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svc-evenements
  template:
    metadata:
      labels:
        app: svc-evenements
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3005"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: svc-evenements
        image: svc-evenements:v4
        imagePullPolicy: Never
        ports:
        - containerPort: 3005
        env:
        - name: PORT
          value: "3005"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DB_URL_EVENTS
        - name: KAFKA_BROKER
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: KAFKA_BROKER
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-collector-opentelemetry-collector:4317"
        - name: OTEL_SERVICE_NAME
          value: "svc-evenements"
        - name: KAFKAJS_NO_PARTITIONER_WARNING
          value: "1"
        - name: KEYCLOAK_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: KEYCLOAK_URL
        - name: KEYCLOAK_REALM
          value: "flotte"
        resources:
          limits:
            memory: 256Mi
            cpu: "250m"
          requests:
            memory: 128Mi
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3005
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3005
          initialDelaySeconds: 10
          periodSeconds: 5
