apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-localisation
  namespace: flotte-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svc-localisation
  template:
    metadata:
      labels:
        app: svc-localisation
    spec:
      containers:
      - name: svc-localisation
        image: svc-localisation:dev
        imagePullPolicy: Never
        ports:
        - containerPort: 3004
        env:
        - name: PORT
          value: "3004"
        resources:
          limits:
            memory: 256Mi
            cpu: "250m"
          requests:
            memory: 128Mi
            cpu: "100m"
