apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-vehicules
  namespace: flotte-dev
  labels:
    app: svc-vehicules
spec:
  replicas: 2
  selector:
    matchLabels:
      app: svc-vehicules
  template:
    metadata:
      labels:
        app: svc-vehicules
    spec:
      containers:
        - name: svc-vehicules
          image: svc-vehicules:v3
          imagePullPolicy: Never
          ports:
            - containerPort: 3001
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_URL_VEHICLES
            - name: KAFKA_BROKER
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: KAFKA_BROKER
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector-opentelemetry-collector:4317"
            - name: PORT
              value: "3001"
            - name: KEYCLOAK_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: KEYCLOAK_URL
            - name: KEYCLOAK_REALM
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: KEYCLOAK_REALM
          readinessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: svc-vehicules
  namespace: flotte-dev
spec:
  selector:
    app: svc-vehicules
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP